### ISSUE TITLE
Does not successfully deploy to Netlify

### ISSUE THREAD

**Issue by dennisregalado** [mittalyashu/gridsome-starter-netlifycms#1]

**Comment by mittalyashu** [comment]
Can you share some more detail about the error you are getting while deploying?

**Comment by huphtur** [comment]
```
4:01:58 PM: Build ready to start
4:06:10 PM: build-image version: 84aca9ba39e0ee86ba194760fbfc51a808f62543
4:06:10 PM: buildbot version: ae7eabf6c88cc6c45c19fb821f4b0a1c2a55238d
4:06:10 PM: Fetching cached dependencies
4:06:11 PM: Failed to fetch cache, continuing with build
4:06:11 PM: Starting to prepare the repo for build
4:06:11 PM: No cached dependencies found. Cloning fresh repo
4:06:11 PM: git clone https://github.com/mittalyashu/gridsome-starter-netlifycms
4:06:12 PM: Preparing Git Reference refs/heads/master
4:06:12 PM: Found netlify.toml. Overriding site configuration
4:06:12 PM: Starting build script
4:06:12 PM: Installing dependencies
4:06:13 PM: Downloading and installing node v8.15.1...
4:06:14 PM: Downloading https://nodejs.org/dist/v8.15.1/node-v8.15.1-linux-x64.tar.xz...
4:06:14 PM:         0.3%
4:06:14 PM: 
#####                                                                      8.2%
4:06:14 PM: 
###################################
4:06:14 PM:                                    48.9%
4:06:14 PM: 
###############################
4:06:14 PM: ###########################                81.1%
4:06:14 PM: 
#################################################
4:06:14 PM: ####################### 100.0%
4:06:14 PM: Computing checksum with sha256sum
4:06:14 PM: Checksums matched!
4:06:17 PM: Now using node v8.15.1 (npm v6.4.1)
4:06:17 PM: Attempting ruby version 2.3.6, read from environment
4:06:18 PM: Using ruby version 2.3.6
4:06:19 PM: Using PHP version 5.6
4:06:19 PM: Started restoring cached node modules
4:06:19 PM: Finished restoring cached node modules
4:06:19 PM: Installing NPM modules using NPM version 6.4.1
4:06:57 PM: > sharp@0.21.3 install /opt/build/repo/node_modules/sharp
4:06:57 PM: > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
4:06:57 PM: info
4:06:57 PM: sharp
4:06:57 PM:  Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.0/libvips-8.7.0-linux-x64.tar.gz
4:07:00 PM: > node-sass@4.11.0 install /opt/build/repo/node_modules/node-sass
4:07:00 PM: > node scripts/install.js
4:07:00 PM: Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/linux-x64-57_binding.node
4:07:01 PM: Download complete
4:07:01 PM: Binary saved to /opt/build/repo/node_modules/node-sass/vendor/linux-x64-57/binding.node
4:07:01 PM: Caching binary to /opt/buildhome/.npm/node-sass/4.11.0/linux-x64-57_binding.node
4:07:01 PM: > cwebp-bin@5.0.0 postinstall /opt/build/repo/node_modules/cwebp-bin
4:07:01 PM: > node lib/install.js
4:07:02 PM:   ✔ cwebp pre-build test passed successfully
4:07:02 PM: > mozjpeg@6.0.1 postinstall /opt/build/repo/node_modules/mozjpeg
4:07:02 PM: > node lib/install.js
4:07:02 PM:   ✔ mozjpeg pre-build test passed successfully
4:07:02 PM: > pngquant-bin@5.0.2 postinstall /opt/build/repo/node_modules/pngquant-bin
4:07:02 PM: > node lib/install.js
4:07:03 PM:   ✔ pngquant pre-build test passed successfully
4:07:03 PM: > node-sass@4.11.0 postinstall /opt/build/repo/node_modules/node-sass
4:07:03 PM: > node scripts/build.js
4:07:03 PM: Binary found at /opt/build/repo/node_modules/node-sass/vendor/linux-x64-57/binding.node
4:07:03 PM: Testing binary
4:07:03 PM: Binary is fine
4:07:06 PM: npm notice created a lockfile as package-lock.json. You should commit this file.
4:07:06 PM: npm WARN gridsome-starter-netlifycms@ No repository field.
4:07:06 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
4:07:06 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
4:07:06 PM: added 1283 packages from 655 contributors and audited 17630 packages in 46.236s
4:07:06 PM: found 0 vulnerabilities
4:07:06 PM: NPM modules installed
4:07:06 PM: Started restoring cached go cache
4:07:06 PM: Finished restoring cached go cache
4:07:06 PM: unset GOOS;
4:07:06 PM: unset GOARCH;
4:07:06 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.10.linux.amd64';
4:07:06 PM: export PATH="/opt/buildhome/.gimme/versions/go1.10.linux.amd64/bin:${PATH}";
4:07:06 PM: go version >&2;
4:07:06 PM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.10.linux.amd64.env';
4:07:06 PM: go version go1.10 linux/amd64
4:07:06 PM: Installing missing commands
4:07:06 PM: Verify run directory
4:07:06 PM: Executing user command: gridsome build
4:07:07 PM: Gridsome v0.5.4
4:07:08 PM: Initialize - 0.33s
4:07:08 PM: Load sources - 0.08s
4:07:08 PM: Create GraphQL schema - 0.07s
4:07:08 PM: Set up routes - 0s
4:07:08 PM: Generate code - 0.03s
4:07:08 PM: Bootstrap finish - 0.52s
4:07:08 PM: Run GraphQL (4 queries) - 0.08s
4:07:08 PM: Compiling assets...
4:07:20 PM: Compile assets - 11.55s
4:07:20 PM: Error: stderr is null - this should never happen. Please open up an issue at https://github.com/facebook/jest
4:07:20 PM:     at ChildProcessWorker.getStderr (/opt/build/repo/node_modules/jest-worker/build/workers/ChildProcessWorker.js:235:13)
4:07:20 PM:     at new BaseWorkerPool (/opt/build/repo/node_modules/jest-worker/build/base/BaseWorkerPool.js:69:35)
4:07:20 PM:     at new WorkerPool (/opt/build/repo/node_modules/jest-worker/build/WorkerPool.js:31:1)
4:07:20 PM:     at new JestWorker (/opt/build/repo/node_modules/jest-worker/build/index.js:123:26)
4:07:20 PM:     at createWorker (/opt/build/repo/node_modules/gridsome/lib/workers/index.js:9:10)
4:07:20 PM:     at renderHTML (/opt/build/repo/node_modules/gridsome/lib/build.js:217:18)
4:07:20 PM:     at module.exports (/opt/build/repo/node_modules/gridsome/lib/build.js:40:9)
4:07:20 PM:     at <anonymous>
```

**Comment by mittalyashu** [comment]
The error log you have shared @huphtur, seems like the problem is in the jest package.

I will just test the deployment again and get back to you.

**Comment by mittalyashu** [comment]
From my end the site is deploying perfectly without any error, can you share your repo url @huphtur

**Comment by huphtur** [comment]
Weird, site deployed fine this morning. Perhaps Netlify had some issues?

**Comment by mittalyashu** [comment]
Awesome, glad your were able to deploy your site. 👍🏻

If possible, don't forget to share your website link on this issue, would love to see what you have created using this starter kit. 😋
